Rhythm/Controllers/AboutMeController.cs
using Rhythm.BL.Interfaces;
using Rhythm.Domain.Repository.Interfaces;
using Rhythm.Mappers;
using Rhythm.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Rhythm.Controllers
{
    public class AboutMeController : DefaultController
    {
        private AboutMeMapper _aboutMeMapper;

        public AboutMeController(IUserProvider userProvider, IPortfolioProvider portfolioProvider, AboutMeMapper aboutMeMapper)
        {
            _userProvider = userProvider;
            _portfolioProvider = portfolioProvider;
            _aboutMeMapper = aboutMeMapper;
        }

        public async Task<ActionResult> Index()
        {
            var user = await _userProvider.GetChiefUsersAsync();
            var portfolio = await _portfolioProvider.GetPortfolioByUserAsync(user.FirstOrDefault().Id);

            var userViewModel = _aboutMeMapper.ToChiefUserViewModel(user.FirstOrDefault(), portfolio);

            return View(userViewModel);
        }

        public async Task<FileContentResult> GetImage(int id)
        {
            var chiefUser = await _userProvider.GetUserAsync(id);

            if (chiefUser.ImagePath != null)
            {
                var dataByte = System.IO.File.ReadAllBytes(chiefUser.ImagePath);

                return File(dataByte, "image/png");
            }

            return null;
        }
    }
}

Rhythm/Controllers/ErrorController.cs
using System.Web.Mvc;

namespace Rhythm.Controllers
{
    /// <summary>
    /// Contains actions to return views for different errors
    /// </summary>
    public class ErrorController : Controller
    {
        /// <summary>
        /// Retutn view for generic errors (for ex. Internal Server Error like 500)
        /// </summary>
        /// <returns></returns>

        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// Return view for 404 errors
        /// </summary>
        /// <returns></returns>

        public ActionResult NotFound()
        {
            return View();
        }
    }
}

Rhythm/Controllers/PostsController.cs
using NLog;
using Rhythm.BL.Interfaces;
using Rhythm.Domain.Entities;
using Rhythm.Mappers;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace Rhythm.Controllers
{
    public class PostsController : DefaultController
    {
        private static NLog.Logger logger = LogManager.GetCurrentClassLogger();
        private PostMapper _postMapper;

        public PostsController(IPostProvider postProvider, PostMapper postMapper)
        {
            _postProvider = postProvider;
            _postMapper = postMapper;
        }

        public async Task<ViewResult> Index(int page = 1)
        {
            var post = await _postProvider.GetPostsAsync();
            var postListViewModel = _postMapper.ToPostListViewModel(post, page);

            return View(postListViewModel);
        }

        public async Task<ActionResult> Post(int id, bool? flag)
        {
            var posts = await _postProvider.GetPostsAsync();
            int count = posts.Where(p => p.Published == true).Max(m => m.Id);

            var post = await _postProvider.GetPostWithConditionAsync(id, flag);

            var postSingleViewModel = _postMapper.ToPostSingleViewModel(post, count);

            return View(postSingleViewModel);
        }

        public async Task<FileContentResult> GetImage(int id)
        {
            var post = await _postProvider.GetPostAsync(id);

            if (post.ImagePath != null)
            {
                var dataByte = System.IO.File.ReadAllBytes(post.ImagePath);

                return File(dataByte, "image/png");
            }

            return null;
        }
    }
}

Rhythm/Controllers/RssController.cs
using Rhythm.BL.Interfaces;
using Rhythm.Domain.Entities;
using Rhythm.Mappers;
using Rhythm.Models;
using Rhythm.Models.RssFeeds;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Rhythm.Controllers
{
    public class RssController : DefaultController
    {
        private RssMapper _rssMapper;
        private RssCore _rssCore;

        public RssController(IRssProvider rssProvider, RssMapper rssMapper, RssCore rssCore)
        {
            _rssProvider = rssProvider;
            _rssMapper = rssMapper;
            _rssCore = rssCore;
        }

        public async Task<ActionResult> Index(int page = 1)
        {
            var rsses = await _rssProvider.GetRssesAsync();
            var rssesViewModel = _rssMapper.ToRssesViewModel(rsses, page);

            return View(rssesViewModel);
        }

        public async Task<ActionResult> GetRss(int id, int page = 1)
        {
            var rss = await _rssProvider.GetRssAsync(id);
            var rssFeed = CheckType(rss);
            var rssListViewModel = _rssMapper.ToRssListViewModel(rss, rssFeed, page);

            return View(rssListViewModel);
        }

        private List<RssViewModel> CheckType(Rss rss)
        {
            List<RssViewModel> rssFeed;

            switch (rss.Type)
            {
                case TypeRss.Xml:
                    return rssFeed = _rssCore.GetRssFeedXml(rss.Url);
                case TypeRss.Atom:
                    return rssFeed = _rssCore.GetRssFeedAtom(rss.Url);
                case TypeRss.Common:
                    return rssFeed = _rssCore.GetRssFeedCommon(rss.Url);
                default:
                    return rssFeed = _rssCore.GetRssFeedCommon(rss.Url);
            }
        }

        //#region SergeyTeplyakov
        //public ActionResult Sergeyteplyakov(string src, int page = 1)
        //{
        //    var n = RssReader.GetRssFeed("sergeyteplyakov");
        //    RssListViewModel model = new RssListViewModel
        //    {
        //        Source = src,

        //        RssReaders = n.OrderBy(m => m.PubDate)
        //        .AsEnumerable()
        //        .Reverse()
        //        .Skip((page - 1) * PageSize)
        //        .Take(PageSize),

        //        PagingView = new ListView
        //        {
        //            CurrentPage = page,
        //            PostsPerPage = PageSize,
        //            TotalPosts = n.Count()
        //        }
        //    };

        //    ViewBag.Title = "Sergey Teplyakov";
        //    ViewBag.WordFirst = "NEWS";
        //    ViewBag.WordSecond = "IT";
        //    ViewBag.WordThird = "Blog";

        //    ViewBag.Site = "Sergey Teplyakov";
        //    ViewBag.News = "News";
        //    return View("RSS", model);
        //}
        //#endregion
    }
}

Rhythm/Controllers/SearchController.cs
using Rhythm.BL.Interfaces;
using Rhythm.Domain.Entities;
using Rhythm.Mappers;
using Rhythm.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Rhythm.Controllers
{
    public class SearchController : DefaultController
    {
        private SearchResultMapper _searchResultMapper;
        public SearchController(IPostProvider postProvider, SearchResultMapper searchResultMapper, ICategoryProvider categoryProvider, ITagProvider tagProvider)
        {
            _postProvider = postProvider;
            _categoryProvider = categoryProvider;
            _tagProvider = tagProvider;
            _searchResultMapper = searchResultMapper;
        }

        public async Task<ViewResult> Category(int id, int page = 1)
        {
            var posts = await _postProvider.GetPostsByCategoryAsync(id);
            var category = await _categoryProvider.GetCategoryAsync(id);

            var categorySearchResultViewModel = _searchResultMapper.ToCategoryResultViewModel(posts, page, category.Name);

            return View("Index", categorySearchResultViewModel);
        }

        public async Task<ViewResult> Tag(int id, int page = 1)
        {
            var posts = await _postProvider.GetPostsByTagAsync(id);
            var tag = await _tagProvider.GetTagAsync(id);

            var tagSearchResultViewModel = _searchResultMapper.ToTagResultViewModel(posts, page, tag.Name);

            return View("Index", tagSearchResultViewModel);
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public async Task<ViewResult> Index(string searchText, int page = 1)
        {
            var posts = await _postProvider.GetPostsByTextAsync(searchText);
            SearchResultViewModel searchResultViewModel;

            if (posts == null)
            {
                searchResultViewModel = _searchResultMapper.ToSearchResultViewModel(posts, page, searchText);

                return View("Index", searchResultViewModel);
            }

            searchResultViewModel = _searchResultMapper.ToSearchResultViewModel(posts, page, searchText);

            return View("Index", searchResultViewModel);
        }

        public async Task<ViewResult> Archive(string yearModel, string monthModel, int page = 1)
        {
            int year;
            Int32.TryParse(yearModel, out year);
            int month;
            Int32.TryParse(monthModel, out month);

            var posts = await _postProvider.GetPostsByArchiveAsync(year, month);

            var archiveSearchResultViewModel = _searchResultMapper.ToArchiveResultViewModel(posts, page, yearModel, monthModel);

            //ViewBag.Title = "Archive result";
            //if (Year == null && Month == null)
            //{
            //    ViewBag.Text = String.Format(@"Your search - ""{0}, {1}"" - did not match any documents.", Year, Month);
            //}
            //else
            //{
            //    ViewBag.Text = String.Format(@"List of posts found for search archive year - ""{0}"", month - ""{1}""", Year, Month);
            //}

            return View("Index", archiveSearchResultViewModel);
        }
    }
}

Rhythm/Views/Shared/_CommentsList.cshtml
@*@model Rhythm.Models.PostViewModel

<!-- Comments -->
<div class="mb-80 mb-xs-40">
    @if (Model.Post.CountComments == 0)
    {
        <h5 class="blog-page-title font-alt">No Comments<small class="number">, would you like to leave a comment?</small></h5>
    }
    else
    {
        <h4 class="blog-page-title font-alt">Comments<small class="number">(@Model.Post.CountComments)</small></h4>
        <ul class="media-list text comment-list clearlist">
            @Html.Action("AllComments", "Comments")
        </ul>
    }
    <!-- End Comments -->
    <br />
    <h4 class="blog-page-title font-alt" id="add">Add Comment</h4>

    <!-- Form -->
    @using (Html.BeginForm("Post", "Posts", FormMethod.Post, new { @class = "form contact-form" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary("", new { @class = "form-tip pt-20", @style = "color:red;" })
        <div class="validation-summary-error" data-valmsg-summary="true">
            <div class="row mb-20 mb-md-10">
                <div class="col-md-6 mb-md-10">
                    <!-- Name -->
                    @Html.TextBoxFor(model => model.Comment.NameUserSender, new { @class = "input-md form-control required", @placeholder = "Name" })
                </div>
                <div class="col-md-6">
                    <!-- Email -->
                    @Html.TextBoxFor(model => model.Comment.EmailUserSender, new { @class = "input-md form-control required", @placeholder = "Email" })
                </div>
            </div>
            <!-- Comment -->
            <div class="mb-30 mb-md-10">
                @Html.TextAreaFor(model => model.Comment.Comment1, new { @class = "input-md form-control required", rows = "6", @placeholder = "Comment" })
            </div>
            <div class="mb-30 mb-md-10">
                <label class="hs-line-4 font-alt black">Are you like Dogs?</label>
                @Html.CheckBoxFor(model => model.Comment.DescriptionComment)
            </div>
            @Html.HiddenFor(m => m.Post.ID)
            <!-- Send Button -->
            <button type="submit" value="Submit" class="btn btn-mod btn-medium btn-round btn-round">
                Send comment
            </button>
        </div>
    }
</div>

<!-- End Contact Section -->
@section scripts {
    <script>
        jQuery.validator.addMethod("isvalidbool", function (value, element, param) {
            return element.checked;
        });
        jQuery.validator.unobtrusive.adapters.addBool("isvalidbood");
    </script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
}*@

Rhythm/Views/Shared/_Error.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- Page Wrap -->
<div class="page" id="top">
    <!-- Home Section -->
    <section class="home-section bg-dark-alfa-50 parallax-2" data-background="images/full-width-images/section-bg-12.jpg">
        <div class="js-height-full">

            <!-- Hero Content -->
            <div class="home-content container">
                <div class="home-text">
                    <div class="hs-cont">

                        <!-- Headings -->
                        <div class="hs-wrap">

                            <div class="hs-line-13 font-alt mb-10">
                                404
                            </div>

                            <div class="hs-line-4 font-alt mb-40">
                                The page you were looking for could not be found.
                            </div>

                            <div class="local-scroll">
                                <a href="@Html.ActionLink("Index", "Home")" class="btn btn-mod btn-w btn-round btn-small"><i class="fa fa-angle-left"></i> Back To Home Page</a>
                            </div>

                        </div>
                        <!-- End Headings -->

                    </div>
                </div>
            </div>
            <!-- End Hero Content -->

        </div>
    </section>
    <!-- End Home Section -->
    <!-- Navigation panel -->
    <nav class="main-nav dark transparent stick-fixed">
        <div class="full-wrapper relative clearfix">
            <!-- Logo ( * your text or image into link tag *) -->
            <div class="nav-logo-wrap local-scroll">
                <a href="mp-index.html" class="logo">
                    <img src="images/logo-white.png" alt="" />
                </a>
            </div>
            <div class="mobile-nav">
                <i class="fa fa-bars"></i>
            </div>
            <!-- Main Menu -->
            <div class="inner-nav desktop-nav">
                <ul class="clearlist scroll-nav local-scroll">
                    <li class="active"><a href="mailto:justadreampictures@gmail.com"><i class="fa fa-envelope"></i> justadreampictures@gmail.com</a></li>
                    <li><a href="#"><i class="fa fa-phone"></i> 0307-567-890</a></li>

                </ul>
            </div>
        </div>
    </nav>
    <!-- End Navigation panel -->
</div>

Rhythm/Views/Shared/_HeadSection.cshtml
@model Rhythm.Models.HeaderViewModel

<!-- Head Section -->
<section class="small-section bg-gray-lighter">
    <div class="relative container align-left">
        <div class="row">
            <div class="col-md-8">
                <h1 class="hs-line-11 font-alt mb-20 mb-xs-0">@Model.Title</h1>
                <div class="hs-line-4 font-alt black">
                    @Model.Text
                </div>
            </div>
            @if (Model.FirstTagWord != "" && Model.SecondTagWord != "" && Model.ThirdTagWord != "")
            {
                <div class="col-md-4 mt-30">
                    <div class="mod-breadcrumbs font-alt black align-right">
                        <a>@Model.FirstTagWord</a>&nbsp;/&nbsp;<a>@Model.SecondTagWord</a>&nbsp;/&nbsp;<a>@Model.ThirdTagWord</a>
                    </div>
                </div>
            }
        </div>
    </div>
</section>
<!-- End Head Section -->

Rhythm/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <!--TODO: add SEO - keyword, description, content, author and robotics-->
    <title>@ViewBag.Title</title>
    <meta name="description" content="Simple blog by Vladimir Makarevich. Программирование на C#, .NET и WEB разработке, блог Владимира Макаревича и все о MVC, ASP.NET, Core, Azure, Microsoft.">
    <meta name="keywords" content="Программирование на C#, .NET, Microsoft, CLR, Core, ASP.NET MVC, ASP, Programming, HTML5, CSS3, JavaScript, blog, простой блог, исходные коды, обучение, обучающие материалы">
    <meta charset="utf-8">
    <meta name="author" content="Vladimir Makarevich">
    <!--[if IE]><meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'><![endif]-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />

    <!-- Favicons -->
    <link rel="shortcut icon" href="~/Content/img/favicon.png">
    <link rel="apple-touch-icon" href="~/Content/img/apple-touch-icon.png">
    <link rel="apple-touch-icon" sizes="72x72" href="~/Content/img/apple-touch-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="114x114" href="~/Content/img/apple-touch-icon-114x114.png">

    @Styles.Render("~/Content/Style")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body class="appear-animate">
    <!-- Page Loader -->
    <div class="page-loader">
        <div class="loader">Loading...</div>
    </div>
    <!-- End Page Loader -->
    <!-- Page Wrap -->
    <div class="page" id="top">
        <!-- Section -->

        @RenderBody()
        <!-- End Section -->
        <!-- Footer -->
        <footer class="page-section bg-gray-lighter footer pb-60">
            <div class="container">
                <!-- Footer Logo -->
                <div class="local-scroll mb-30 wow fadeInUp" data-wow-duration="1.5s">
                    <a href="#top"><img src="~/Content/img/logo-footer.png" width="78" height="36" alt="" /></a>
                </div>
                <!-- End Footer Logo -->
                <!-- TODO: Social Links -->
                <div class="footer-social-links mb-110 mb-xs-60">
                    <a href="https://github.com/VladimirMakarevich" title="GitHub" target="_blank"><i class="fa fa-angle-down"></i></a>
                    <a href="https://www.linkedin.com/in/vladimir23" title="LinkedIn" target="_blank"><i class="fa fa-angle-down"></i></a>
                    <a href="https://github.com/VladimirMakarevich" title="GitHub" target="_blank"><i class="fa fa-angle-down"></i></a>
                    <a href="https://www.linkedin.com/in/vladimir23" title="LinkedIn" target="_blank"><i class="fa fa-angle-down"></i></a>
                    <a href="https://github.com/VladimirMakarevich" title="GitHub" target="_blank"><i class="fa fa-angle-down"></i></a>
                </div>
                <!-- End Social Links -->
                <!-- Footer Text -->
                <div class="footer-text">
                    <!-- Copyright -->
                    <div class="footer-copy font-alt">
                        <a href="https://github.com/VladimirMakarevich" target="_blank">&copy; @DateTime.Now.Year</a>.
                    </div>
                    <!-- End Copyright -->
                    <div class="footer-made">
                        Vladimir Makarevich - ASP.NET MVC Developer
                    </div>
                </div>
                <!-- End Footer Text -->
            </div>
            <!-- Top Link -->
            <div class="local-scroll">
                <a href="#top" class="link-to-top"><i class="fa fa-caret-up"></i></a>
            </div>
            <!-- End Top Link -->
        </footer>
        <!-- End Foter -->
    </div>
    <!-- End Page Wrap -->
    @Scripts.Render("~/bundles/rhythm/jquery")
    @Scripts.Render("~/bundles/rhythm/jqueryval")
    @Scripts.Render("~/bundles/rhythm/allJS")
    <!--[if lt IE 10]><script type="text/javascript" src="~/Script/rhythm/placeholder.js"></script><![endif]-->
    @RenderSection("scripts", required: false)
</body>
</html>

Rhythm/Views/Shared/_NavigationPanel.cshtml
        <!-- Navigation panel -->
<nav class="main-nav js-stick">
    <div class="full-wrapper relative clearfix">
        <!-- Logo ( * your text or image into link tag *) -->
        <div class="nav-logo-wrap local-scroll">
            <a href="@Url.Action("Index", "Home")" class="logo">
                <img src="~/Content/img/logo-dark.png" alt="" />
            </a>
        </div>
        <div class="mobile-nav">
            <img src="" alt="" />
            <i class="fa fa-bars"></i>
        </div>

        <!-- Main Menu -->
        <div class="inner-nav desktop-nav">
            <ul class="clearlist">
                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                <li>@Html.ActionLink("Post", "Index", "Posts")</li>
                <li>@Html.ActionLink("Rss Feeds", "Index", "Rss")</li>
                @*<li>@Html.ActionLink("Library", "Index", "Library")</li>*@
                <li>@Html.ActionLink("Portfolio", "Index", "Portfolio")</li>
                <li>@Html.ActionLink("About me", "Index", "AboutMe")</li>
                <li>@Html.ActionLink("Contact", "Index", "Contacts")</li>
                <li>
                </li>
            </ul>
        </div>
        <!-- End Main Menu -->
    </div>
</nav>
<!-- End Navigation panel -->

Rhythm/Views/Shared/_Sidebar.cshtml
@*@model Rhythm.Models.RecentViewModel.RecentContentViewModel*@

<!-- Sidebar -->
<div class="col-sm-4 col-md-3 col-md-offset-1 sidebar">
    <!-- TODO: Search Widget -->
    <div class="widget">
        @using (Html.BeginForm("Index", "Search", FormMethod.Post, new { @class = "form-inline form", @role = "form" }))
        {
            @Html.AntiForgeryToken()
            <div class="search-wrap">
                <button class="search-button animate" type="submit" title="Start Search">
                    <i class="fa fa-search"></i>
                </button>
                @Html.TextBox("searchText", "", new { @class = "form-control search-field", @placeholder = "Search..." })
            </div>
        }
    </div>
    <!-- End Search Widget -->
    <div class="widget">
        @*<h5 class="widget-title font-alt">Categories</h5>
            <div class="widget-body" id="recentCategories">
                <ul class="clearlist widget-menu">
                    @foreach (var category in @Model.CategoryRecentViewModel)
                    {
                        <li>
                            <a href="@Url.Action("Category", "Search", new { id = category.Id, Name = category.Name })" title="@category.Name">@category.Name</a>
                            <small>
                                - @category.CountCategory
                            </small>
                            <div class="fa fa-examples">
                                <i class="fa fa-fw">&#xf0a5</i>
                            </div>
                        </li>

                    }
                </ul>
            </div>*@
        @Html.Action("RecentCategories", "Recents")
    </div>
    <!-- End Widget -->
    <div class="widget">
        @*<h5 class="widget-title font-alt">Tags</h5>
            <div class="widget-body">
                <div class="tags">
                    @foreach (var tag in Model.TagRecentViewModel)
                    {
                        <a href="@Url.Action("Tag", "Search", new { id = tag.Id, Name = tag.Name })" title="@tag.Name">@tag.Name</a>
                        @Html.Hidden(tag.Name)
                    }
                </div>
            </div>*@
        @Html.Action("RecentTags", "Recents")
    </div>
    <!-- End Widget -->
    <div class="widget">
        @*<h5 class="widget-title font-alt">Last posts</h5>
            <div class="widget-body">
                <ul class="clearlist widget-posts">
                    @foreach (var post in Model.PostRecentViewModel)
                    {
                        <li class="clearfix">
                            <div class="widget-posts-descr">
                                <a href="@Url.Action("Post","Posts", new { id = post.Id})" title="@post.Title">@post.Title</a>
                                Posted by @post.NameSenderPost in @post.PostedOn
                            </div>
                            <div class="fa fa-examples">
                                <i class="fa fa-fw">&#xf0f6</i>
                                <i class="fa fa-fw">&#xf0f6</i>
                                <i class="fa fa-fw">&#xf0f6</i>
                            </div>
                        </li>
                    }
                </ul>
            </div>*@
        @Html.Action("RecentPosts", "Recents")
    </div>
    <!-- End Widget -->
    <div class="widget">
        @*
                <h5 class="widget-title font-alt">Comments</h5>
                        <div class="widget-body">
                <ul class="clearlist widget-comments">
                    @foreach (var comment in Model.CommentRecentViewModel)
                    {
                        <li>
                            @comment.NameUserSender on <a href="@Url.Action("Post","Posts", new { id = comment.Id } )" title="@comment.CommentContent">@comment.CommentContent (@comment.PostAddedDate)</a>
                            <div class="fa fa-examples">
                                <i class="fa fa-fw">&#xf0e5</i>
                                <i class="fa fa-fw">&#xf0e5</i>
                                <i class="fa fa-fw">&#xf0e5</i>
                            </div>
                        </li>

                    }
                </ul>
            </div>*@
        @Html.Action("RecentComments", "Recents")
    </div>
    <!-- End Widget -->
    <!-- TODO: Widget Articles-->
    <div class="widget">
        @*<h5 class="widget-title font-alt">Text widget</h5>
            <div class="widget-body">
                <div class="widget-text clearfix">
                    @if (Model.ArticleWidgetViewModel.ImageData != null)
                    {
                        <img width="200" height="133" src="@Url.Action("GetImage", "Posts", new { Model.ArticleWidgetViewModel.Id })" />
                    }
                    <br /><br />
                    <h2 class="blog-item-title">
                        @Html.ActionLink(Model.ArticleWidgetViewModel.Title, "Post", "Posts", new { id = Model.ArticleWidgetViewModel.Id }, new { @class = "" })
                    </h2>
                    @Html.Raw(Model.ArticleWidgetViewModel.ArticleContent)
                </div>
            </div>*@

        @Html.Action("RecentArticleWidgets", "Recents")
    </div>
    <!-- End Widget -->
    <!-- TODO: Widget Archove-->
    <div class="widget">
        @Html.Action("RecentArchives", "Recents")
    </div>
    <!-- End Widget -->
</div>
<!-- End Sidebar -->

Rhythm/Views/Shared/_messageNote.cshtml
<!-- Section -->
<section class="page-section">
    <div class="container relative">
        <!-- Row -->
        <div class="row">
            <!-- Col -->
            <div class="col-md-8 col-md-offset-2">
                <!-- Info Message -->
                @*<div class="alert info">
                    <i class="fa fa-lg fa-comments-o"></i>
                </div>*@
                <!-- Success Message -->
                @*<div class="alert success">
                    <i class="fa fa-lg fa-check-circle-o"></i> Sorry, but this section is still under construction
                </div>*@
                <!-- Notice Message -->
                <div class="alert notice">
                    <i class="fa fa-lg fa-exclamation-triangle"></i> Sorry, but this section is still under construction
                </div>
                <!-- Error Notice -->
                @*<div class="alert error">
                    <i class="fa fa-lg  fa-times-circle"></i>
                </div>*@
            </div>
            <!-- End Col -->
        </div>
        <!-- End Row -->
    </div>
</section>
<!-- End Section -->