Rhythm/Areas/ChiefAdmin/Models/CategoryViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Rhythm.Areas.ChiefAdmin.Models
{
    public class CategoryViewModel
    {
        public int ID { get; set; }
        [Required(ErrorMessage = "the field are required!")]
        public string Name { get; set; }
        [Required(ErrorMessage = "the field are required!")]
        public string UrlSlug { get; set; }
        public string DescriptionCategory { get; set; }
        public int CountCategory { get; set; }
    }
}

Rhythm/Areas/ChiefAdmin/Models/CommentViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace Rhythm.Areas.ChiefAdmin.Models
{
    public class CommentViewModel
    {

        public int ID { get; set; }
        public int PostID { get; set; }
        [Required(ErrorMessage = "the field are required!")]
        public string NameUserSender { get; set; }
        [Required(ErrorMessage = "the field are required!")]
        public string EmailUserSender { get; set; }
        [Required(ErrorMessage = "the field are required!")]
        public bool DescriptionComment { get; set; }
        public string Comment1 { get; set; }
        public DateTime PostedOn { get; set; }
    }
}

Rhythm/Areas/ChiefAdmin/Models/ImageViewModel.cs
using System.Web;

namespace Rhythm.Areas.ChiefAdmin.Models
{
    public class ImageViewModel
    {
        public int PostID { get; set; }
        public HttpPostedFileBase ImageData { get; set; }
        public byte[] ImageDataByte { get; set; }
        public string ImageMime { get; set; }
    }
}

Rhythm/Areas/ChiefAdmin/Models/PostViewModel.cs
using Rhythm.Domain.Model;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Rhythm.Areas.ChiefAdmin.Models
{
    public class PostViewModel
    {
        [Required(ErrorMessage = "the field are required!")]
        public string NameSenderPost { get; set; }
        [Required(ErrorMessage = "the field are required!")]
        public string Title { get; set; }
        [Required(ErrorMessage = "the field are required!")]
        public string ShortDescription { get; set; }
        [Required(ErrorMessage = "the field are required!")]
        public string DescriptionPost { get; set; }
        [Required(ErrorMessage = "the field are required!")]
        public string UrlSlug { get; set; }
        [Required(ErrorMessage = "the field are required!")]
        public bool Published { get; set; }
        [Required(ErrorMessage = "the field are required!")]
        public int Category { get; set; }
        public Category Category1 { get; set; }
        public byte[] ImageData { get; set; }
        public string ImageMime { get; set; }

        public int ID { get; set; }
        public DateTime PostedOn { get; set; }
        public Nullable<DateTime> Modified { get; set; }
        public Nullable<int> CountComments { get; set; }
        public ICollection<Comment> Comments { get; set; }
        public ICollection<Tag> Tags { get; set; }
    }
}

Rhythm/Areas/ChiefAdmin/Models/TagViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Rhythm.Areas.ChiefAdmin.Models
{
    public class TagViewModel
    {
        [Required(ErrorMessage = "the field are required!")]
        public int ID { get; set; }
        [Required(ErrorMessage = "the field are required!")]
        public string Name { get; set; }
        [Required(ErrorMessage = "the field are required!")]
        public string UrlSlug { get; set; }
        public string DescriptionTag { get; set; }
        public bool Assigned { get; set; }
    }
}

Rhythm/Models/CommentViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Rhythm.Models
{
    public class CommentViewModel
    {
        public int ID { get; set; }
        public int PostID { get; set; }
        [Required(ErrorMessage = "all the fields are required")]
        public string NameUserSender { get; set; }
        [Required(ErrorMessage = "all the fields are required")]
        [EmailAddress(ErrorMessage = "the Email field is not a valid e - mail addres")]
        public string EmailUserSender { get; set; }
        [Required(ErrorMessage = "all the fields are required")]
        [IsValidBool]
        public bool DescriptionComment { get; set; }
        [Required(ErrorMessage = "all the fields are required")]
        public string Comment1 { get; set; }
    }
}

Rhythm/Models/PostViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Rhythm.Models
{
    public class PostViewModel
    {
        public int Id { get; set; }
        public string NameSenderPost { get; set; }
        public string Title { get; set; }
        public string ShortDescription { get; set; }
        public string DescriptionPost { get; set; }
        public string UrlSlug { get; set; }
        public bool Published { get; set; }
        public DateTime PostedOn { get; set; }
        public DateTime Modified { get; set; }
        public byte[] ImageData { get; set; }
        public string ImagePath { get; set; }
        public string ImageMime { get; set; }
        public int CountComments { get; set; }
    }
}

Rhythm/Areas/ChiefAdmin/Controllers/UpdateController.cs
using Rhythm.Areas.ChiefAdmin.Models;
using Rhythm.BL.Interfaces;
using Rhythm.Mappers.ChiefAdmin;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Rhythm.Areas.ChiefAdmin.Controllers
{
    [Authorize]
    public class UpdateController : DefaultController
    {
        private TagAdminMapper _tagMapper;
        private CategoryAdminMapper _categoryMapper;
        private PostAdminMapper _postMapper;
        private CommentAdminMapper _commentMapper;

        public UpdateController(IPostProvider postProvider, ICategoryProvider categoryProvider, ITagProvider tagProvider,
            ICommentProvider commentProvider, TagAdminMapper tagMapper, CategoryAdminMapper categoryMapper,
            PostAdminMapper postMapper, CommentAdminMapper commentMapper)
        {
            _postProvider = postProvider;
            _categoryProvider = categoryProvider;
            _tagProvider = tagProvider;
            _commentProvider = commentProvider;
            _tagMapper = tagMapper;
            _categoryMapper = categoryMapper;
            _postMapper = postMapper;
            _commentMapper = commentMapper;
        }

        #region post
        public async Task<ActionResult> Post(int id)
        {
            var post = await _postProvider.GetPostAsync(id);

            var postViewModel = _postMapper.ToPostViewModel(post);

            await DropDownListCategory(postViewModel.Category);
            await TagData(postViewModel);

            return View(postViewModel);
        }

        [HttpPost]
        [ValidateInput(false)]
        public async Task<ActionResult> Post(PostAdminViewModel postViewModel, int[] selectedTag)
        {
            //var listTag = new List<Tag>();
            //foreach (var item in selectedTag)
            //{
            //    var tag = _repository.Tag.SingleOrDefault(m => m.ID == item);
            //    listTag.Add(tag);
            //}
            //var category = _repository.Category.SingleOrDefault(m => m.ID == postViewModel.Category);

            //postViewModel.Tags = listTag;
            //postViewModel.Category = category;

            //IMapper model = MappingConfig.MapperConfigPost.CreateMapper();
            //Post context = model.Map<Post>(post);

            //await _repository.ChangePostAsync(context);


            var tags = await _tagProvider.GetTagsByIdAsync(selectedTag);
            var categories = await _categoryProvider.GetCategoriesAsync();

            var category = categories.SingleOrDefault(m => m.Id == postViewModel.CategoryId);

            var post = _postMapper.ToPost(postViewModel, tags.ToList(), category);

            await _postProvider.ChangePostAsync(post);

            return RedirectToAction("listPosts", "Home");
        }
        #endregion

        #region image
        public async Task<ActionResult> Image(int id)
        {
            var post = await _postProvider.GetPostAsync(id);
            var imageViewModel = _postMapper.ToImageViewModel(post);

            return View(imageViewModel);
        }

        [HttpPost]
        public async Task<ActionResult> Image(ImageAdminViewModel imageViewModel)
        {
            var post = await _postProvider.GetPostAsync(imageViewModel.Id);
            var filePath = SaveFileData(imageViewModel);
            var postEdited = _postMapper.FromImagePathToPost(filePath, imageViewModel.ImageMime, post);

            await _postProvider.ChangePostAsync(postEdited);

            return RedirectToAction("listPosts", "Home");
        }

        #endregion

        #region tag
        public async Task<ActionResult> Tag(int id)
        {
            var tag = await _tagProvider.GetTagAsync(id);
            var tagViewModel = _tagMapper.ToTagViewModel(tag);

            return View(tagViewModel);
        }

        [HttpPost]
        public async Task<ActionResult> Tag(TagAdminViewModel tagViewModel)
        {
            var tag = _tagMapper.ToTag(tagViewModel);
            await _tagProvider.ChangeTagAsync(tag);

            return RedirectToAction("listTags", "Home");
        }
        #endregion

        #region category
        public async Task<ActionResult> Category(int id)
        {
            var category = await _categoryProvider.GetCategoryAsync(id);
            var categoryVeiwModel = _categoryMapper.ToCategoryViewModel(category);

            return View(categoryVeiwModel);
        }

        [HttpPost]
        public async Task<ActionResult> Category(CategoryAdminViewModel categoryViewModel)
        {
            var category = _categoryMapper.ToCategory(categoryViewModel);
            await _categoryProvider.ChangeCategoryAsync(category);

            return RedirectToAction("listCategories", "Home");
        }
        #endregion

        #region comment
        public async Task<ActionResult> Comment(int id)
        {
            var comment = await _commentProvider.GetCommentAsync(id);
            var commentViewModel = _commentMapper.ToCommentViewModel(comment);

            return View(commentViewModel);
        }

        [HttpPost]
        public async Task<ActionResult> Comment(CommentAdminViewModel commentViewModel)
        {
            var comment = _commentMapper.ToComment(commentViewModel);
            await _commentProvider.ChangeCommentAsync(comment);

            return RedirectToAction("listComments", "Home");
        }
        #endregion

        #region drop
        private void TagDatas(PostAdminViewModel post)
        {

        }
        private async Task TagData(PostAdminViewModel post)
        {
            var tags = await _tagProvider.GetTagsAsync();
            var postTag = new HashSet<int>(post.Tags.Select(c => c.Id));

            var tagsViewModel = _tagMapper.ToTagsViewModelByPostTag(tags, postTag);

            ViewBag.Tag = tagsViewModel;
        }

        private async Task DropDownListCategory(object selectedItem = null)
        {
            var categories = from m in await _categoryProvider.GetCategoriesAsync()
                             orderby m.Id
                             select m;
            var categoriesViewModel = _categoryMapper.ToCategoriesViewModel(categories);

            ViewBag.Category = new SelectList(categoriesViewModel, "Id", "Name", selectedItem);
        }
        #endregion

        #region saveData
        private string SaveFileData(ImageAdminViewModel imageViewModel)
        {
            var fileHashName = imageViewModel.FileBase.GetHashCode().ToString();
            var fileFullName = $"{fileHashName}_{imageViewModel.FileBase.FileName}";
            var filePath = Server.MapPath("~/Content/images/" + fileFullName);

            imageViewModel.FileBase.SaveAs(filePath);

            return filePath;
        }
        #endregion
    }
}

Rhythm/Controllers/CommentsController.cs
using Rhythm.BL.Interfaces;
using Rhythm.Mappers;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace Rhythm.Controllers
{
    public class CommentsController : DefaultController
    {
        private CommentMapper _commentMapper;

        public CommentsController(ICommentProvider commentProvider, CommentMapper commentMapper)
        {
            _commentProvider = commentProvider;
            _commentMapper = commentMapper;
        }


        public async Task<ActionResult> AllComments(int id)
        {
            var comments = await _commentProvider.GetCommentsAsync();
            var commentsViewModel = _commentMapper.ToCommentsViewModel(comments);
            //var sortedComments = allComment.OrderBy(c => c.PostID).Where(i => i.PostID == id).ToList();

            return PartialView(commentsViewModel);
        }
    }
}

Rhythm/Controllers/PostsController.cs
using NLog;
using Rhythm.BL.Interfaces;
using Rhythm.Domain.Entities;
using Rhythm.Mappers;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace Rhythm.Controllers
{
    public class PostsController : DefaultController
    {
        private static NLog.Logger logger = LogManager.GetCurrentClassLogger();
        private PostMapper _postMapper;

        public PostsController(IPostProvider postProvider, PostMapper postMapper)
        {
            _postProvider = postProvider;
            _postMapper = postMapper;
        }

        public async Task<ViewResult> Index(int page = 1)
        {
            var post = await _postProvider.GetPostsAsync();
            var postListViewModel = _postMapper.ToPostListViewModel(post, page);

            return View(postListViewModel);
        }

        public async Task<ActionResult> Post(int id, bool? flag)
        {
            var posts = await _postProvider.GetPostsAsync();
            int count = posts.Where(p => p.Published == true).Max(m => m.Id);

            var post = await _postProvider.GetPostWithConditionAsync(id, flag);

            var postSingleViewModel = _postMapper.ToPostSingleViewModel(post, count);

            return View(postSingleViewModel);
        }

        public async Task<FileContentResult> GetImage(int id)
        {
            var post = await _postProvider.GetPostAsync(id);

            if (post.ImagePath != null)
            {
                var dataByte = System.IO.File.ReadAllBytes(post.ImagePath);

                return File(dataByte, "image/png");
            }

            return null;
        }
    }
}

Rhythm/Areas/ChiefAdmin/Views/Update/Category.cshtml
@model Rhythm.Areas.ChiefAdmin.Models.CategoryAdminViewModel

@{
    Layout = "~/Areas/ChiefAdmin/Views/Shared/_Layout.cshtml";
}

<br /><br /><br />
<h2 class="align-center font-alt uppercase">Change Category</h2>
<!-- Section -->
<section class="page-section">
    <div class="container relative">
        <div>
            <a href="@Url.Action("listCategories", "Home")" class="submit_btn btn btn-mod btn-small btn-round" id="submit_btn"> Back to List </a>
        </div>
        <br />

        <!-- Form -->
        @using (Html.BeginForm("Category", "Update", FormMethod.Post, new { @class = "form" }))
        {
            @Html.HiddenFor(m => m.CountCategory)
            @Html.Label("Name: ", new { @for = "exampleInputFile" })
            <div class="mb-20 mb-md-10">
                <!-- Name -->
                @Html.TextBoxFor(m => m.Name, new { @class = "input-md form-control", @placeholder = "Name" })
            </div>

            @Html.Label("UrlSlug: ", new { @for = "exampleInputFile" })
            <div class="mb-20 mb-md-10">
                <!-- Title -->
                @Html.TextBoxFor(m => m.UrlSlug, new { @class = "input-md form-control", @placeholder = "UrlSlug" })
            </div>

            @Html.Label("Descriprion Category: ", new { @for = "exampleInputFile" })
            <div class="mb-20 mb-md-10">
                @Html.TextAreaFor(m => m.DescriptionCategory, new { @class = "input-md round form-control", @style = "height: 84px;", @placeholder = "Descriprion Category" })
            </div>

            <div class="clearfix">
                <div class="cf-left-col">
                    <!-- Inform Tip -->
                    <div class="form-tip pt-20">
                        <i class="fa fa-info-circle"></i> All the fields are required
                    </div>
                </div>
                <div class="cf-right-col">
                    <!-- Send Button -->
                    <div class="align-right pt-10">
                        <button type="submit" class="submit_btn btn btn-mod btn-small btn-round" id="submit_btn">Save Category</button>
                    </div>
                </div>
            </div>
        }
    </div>
</section>

Rhythm/Areas/ChiefAdmin/Views/Update/Comment.cshtml
@model Rhythm.Areas.ChiefAdmin.Models.CommentAdminViewModel

@{
    Layout = "~/Areas/ChiefAdmin/Views/Shared/_Layout.cshtml";
}

<br /><br /><br />
<h2 class="align-center font-alt uppercase">Change comment</h2>
<!-- Section -->
<section class="page-section">
    <div class="container relative">
        <div>
            <a href="@Url.Action("listComments", "Home")" class="submit_btn btn btn-mod btn-small btn-round" id="submit_btn"> Back to List </a>
        </div>
        <br />
        <!-- Form -->
        @using (Html.BeginForm("Comment", "Update", FormMethod.Post, new { @class = "form" }))
        {

            @Html.Label("Name: ", new { @for = "exampleInputFile" })
            <div class="mb-20 mb-md-10">
                <!-- Name -->
                @Html.TextBoxFor(m => m.NameUserSender, new { @class = "input-md form-control", @placeholder = "Name" })
            </div>

            @Html.Label("Description: ", new { @for = "exampleInputFile" })
            <div class="mb-20 mb-md-10">
                <!-- Title -->
                @Html.TextBoxFor(m => m.EmailUserSender, new { @class = "input-md form-control", @placeholder = "Description" })
            </div>

            @Html.Label("Comment: ", new { @for = "exampleInputFile" })
            <div class="mb-20 mb-md-10">
                @Html.TextAreaFor(m => m.CommentMessage, new { @class = "input-md round form-control", @style = "height: 84px;", @placeholder = "Comment" })
            </div>
            @*@Html.HiddenFor(m => m.ID)*@
            @Html.HiddenFor(m => m.PostId)
            @Html.HiddenFor(m => m.PostedOn)
            <div class="clearfix">
                <div class="cf-left-col">
                    <!-- Inform Tip -->
                    <div class="form-tip pt-20">
                        <i class="fa fa-info-circle"></i> All the fields are required
                    </div>
                </div>
                <div class="cf-right-col">
                    <!-- Send Button -->
                    <div class="align-right pt-10">
                        <button type="submit" class="submit_btn btn btn-mod btn-small btn-round" id="submit_btn">Save Comment</button>
                    </div>
                </div>
            </div>
        }
    </div>
</section>

Rhythm/Areas/ChiefAdmin/Views/Update/Image.cshtml
@model Rhythm.Areas.ChiefAdmin.Models.ImageAdminViewModel
@{
    Layout = "~/Areas/ChiefAdmin/Views/Shared/_Layout.cshtml";
}

<br /><br /><br />
<h2 class="align-center font-alt uppercase">Edit Post</h2>
<!-- Section -->
<section class="page-section">
    <div class="container relative">
        <p>
            <div class="form-actions no-color">
                <a href="@Url.Action("listPosts", "Home", new { id = Model.Id })" class="submit_btn btn btn-mod btn-small btn-round" id="submit_btn"> Back to List </a> |
                <a href="@Url.Action("Image", "Delete", new { id = Model.Id } )" class="btn btn-mod btn-round  btn-small"> Delete Image </a>
            </div>
        </p>
        <!-- Form -->
        @using (Html.BeginForm("Image", "Update", FormMethod.Post, new { enctype = "multipart/form-data", @role = "form", @class = "form" }))
            {
            @Html.HiddenFor(m => m.Id)
            @Html.HiddenFor(m => m.ImagePath)
            @Html.Label("Photo Description: ", new { @for = "exampleInputFile" })
            <div class="mb-20 mb-md-10">
                <!-- Description -->
                @Html.TextBoxFor(m => m.ImageMime, new { @name = "ImageMime", @id = "ImageMime", @class = "input-md form-control", @placeholder = "Photo Description" })
            </div>

                @Html.Label("Load Photo: ")
                <div class="mb-20 mb-md-10">
                    @Html.TextBoxFor(m => m.FileBase, new { @type = "file", id = "FileBase", @value = "Save" })
                    <p class="help-block">
                        Choose photo
                    </p>
                </div>
                @Html.Label("Now: ")
                <div class="mb-20 mb-md-10">
                    @if (Model.ImageData != null)
                    {
                        <img width="300" height="300" src="@Url.Action("GetImage", "Home", new { id = Model.Id })" />
                    }
                </div>
                <div class="clearfix">
                    <div class="cf-left-col">
                        <!-- Inform Tip -->
                        <div class="form-tip pt-20">
                            <i class="fa fa-info-circle"></i> All the fields are required
                        </div>
                    </div>
                    <div class="cf-right-col">
                        <!-- Send Button -->
                        <div class="align-right pt-10">
                            <button type="submit" class="submit_btn btn btn-mod btn-small btn-round" id="submit_btn">Save Image</button>
                        </div>
                    </div>
                </div>
        }
    </div>
</section>

Rhythm/Areas/ChiefAdmin/Views/Update/Post.cshtml
@model Rhythm.Areas.ChiefAdmin.Models.PostAdminViewModel

@{
    Layout = "~/Areas/ChiefAdmin/Views/Shared/_Layout.cshtml";
}

<br /><br /><br />
<h2 class="align-center font-alt uppercase">Change Post</h2>
<!-- Section -->
<section class="page-section">
    <div class="container relative">
        <div>
            <a href="@Url.Action("listPosts", "Home")" class="submit_btn btn btn-mod btn-small btn-round" id="submit_btn"> Back to List </a>
        </div>
        <br />

        <!-- Form -->
        @using (Html.BeginForm("Post", "Update", FormMethod.Post, new { @role = "form", @class = "form" }))
        {
            @Html.HiddenFor(m => m.PostedOn)
            @Html.HiddenFor(m => m.ImageMime)
            @Html.HiddenFor(m => m.ImageData)
            @Html.HiddenFor(m => m.CountComments)
            @Html.HiddenFor(m => m.Id)
            @Html.HiddenFor(m => m.ImagePath)
            @Html.Label("Name: ", new { @for = "exampleInputFile" })
            <div class="mb-20 mb-md-10">
                <!-- Name -->
                @Html.TextBoxFor(m => m.NameSenderPost, new { @name = "Name", @id = "Name", @class = "input-md form-control", @placeholder = "Name" })
            </div>

            @Html.Label("Title: ", new { @for = "exampleInputFile" })
            <div class="mb-20 mb-md-10">
                <!-- Title -->
                @Html.TextBoxFor(m => m.Title, new { @name = "Title", @id = "Title", @class = "input-md form-control", @placeholder = "Title" })
            </div>

            @Html.Label("Short Description: ", new { @for = "exampleInputFile" })
            <div class="mb-20 mb-md-10">
                @Html.TextAreaFor(m => m.ShortDescription, new { @name = "ShortDescription", @id = "ShortDescription", @class = "input-md round form-control", @style = "height: 84px;", @placeholder = "Short Description" })
            </div>

            @Html.Label("Post: ", new { @for = "exampleInputFile" })
            <div class="mb-20 mb-md-10">
                @Html.TextAreaFor(m => m.DescriptionPost, new { @name = "PostDescription", @id = "PostDescription", @class = "input-md round form-control", @style = "height: 84px;", @placeholder = "Post" })
            </div>

            @Html.Label("Url Slug: ", new { @for = "exampleInputFile" })
            <div class="mb-20 mb-md-10">
                <!-- URL -->
                @Html.TextBoxFor(m => m.UrlSlug, new { @name = "UrlSlug", @id = "UrlSlug", @class = "input-md form-control", @placeholder = "Url Slug" })
            </div>
            @Html.Label("Published?: ", new { @for = "exampleInputFile" })
            <div class="mb-20 mb-md-10">
                <label class="checkbox-inline">
                    @Html.CheckBoxFor(m => m.Published)
                </label>
            </div>

            @Html.Label("Choose Category: ", new { @for = "exampleInputFile" })
            <div class="mb-20 mb-md-10">
                @Html.DropDownList("CategoryId", (IEnumerable<SelectListItem>)ViewBag.Category)
            </div>
            <div class="mb-20 mb-md-10">
                @Html.Label("Choose Tags: ", new { @for = "exampleInputFile" })
                <table>
                    <tr>
                        @{
                            List<Rhythm.Areas.ChiefAdmin.Models.TagAdminViewModel> tags = ViewBag.Tag;

                            foreach (var tag in tags)
                            {
                                <td>
                                    <input type="checkbox"
                                           name="selectedTag"
                                           value="@tag.Id"
                                           @(Html.Raw(tag.Assigned ? "checked=\"checked\"" : "")) />
                                </td>
                                <td>
                                    <div><a>&nbsp;</a> - @tag.Name <a>&nbsp;</a></div>
                                </td>
                            }
                        }
                    </tr>
                </table>
            </div>
            @Html.LabelFor(m => m.ImageMime, new { @for = "exampleInputFile" })
                            <div class="mb-20 mb-md-10">
                                @if (Model.ImagePath != null)
                                {
                                    <img width="500" height="250" src="@Url.Action("GetImage", "Home", new { id = Model.Id })" />
                                }
                            </div>
                            <div class="clearfix">
                                <div class="cf-left-col">
                                    <!-- Inform Tip -->
                                    <div class="form-tip pt-20">
                                        <i class="fa fa-info-circle"></i> All the fields are required
                                    </div>
                                </div>
                                <div class="cf-right-col">
                                    <!-- Send Button -->
                                    <div class="align-right pt-10">
                                        <button type="submit" class="submit_btn btn btn-mod btn-small btn-round" id="submit_btn">Save Post</button>
                                    </div>
                                </div>
                            </div>
                            }
    </div>
</section>

<script src="~/Scripts/ckeditor/ckeditor.js"></script>
<script type="text/javascript">
    var editor = CKEDITOR.instances['DescriptionPost'];
    if (editor) { editor.destroy(true); }
    CKEDITOR.replace('DescriptionPost', { enterMode: CKEDITOR.ENTER_BR, });
</script>

<script src="~/Scripts/ckeditor/ckeditor.js"></script>
<script type="text/javascript">
    var editor = CKEDITOR.instances['ShortDescription'];
    if (editor) { editor.destroy(true); }
    CKEDITOR.replace('ShortDescription', { enterMode: CKEDITOR.ENTER_BR, });
</script>

Rhythm/Areas/ChiefAdmin/Views/Update/Tag.cshtml
@model Rhythm.Areas.ChiefAdmin.Models.TagAdminViewModel

@{
    Layout = "~/Areas/ChiefAdmin/Views/Shared/_Layout.cshtml";
}

<br /><br /><br />
<h2 class="align-center font-alt uppercase">Change Tag</h2>
<!-- Section -->
<section class="page-section">
    <div class="container relative">
        <div>
            <a href="@Url.Action("listTags", "Home")" class="submit_btn btn btn-mod btn-small btn-round" id="submit_btn"> Back to List </a>
        </div>
        <br />
        <!-- Form -->
        @using (Html.BeginForm("Tag", "Update", FormMethod.Post, new { @class = "form" }))
        {

            @Html.Label("Name: ", new { @for = "exampleInputFile" })
            <div class="mb-20 mb-md-10">
                <!-- Name -->
                @Html.TextBoxFor(m => m.Name, new { @class = "input-md form-control", @placeholder = "Name" })
            </div>

            @Html.Label("UrlSlug: ", new { @for = "exampleInputFile" })
            <div class="mb-20 mb-md-10">
                <!-- Title -->
                @Html.TextBoxFor(m => m.UrlSlug, new { @class = "input-md form-control", @placeholder = "UrlSlug" })
            </div>

            @Html.Label("Description Tag: ", new { @for = "exampleInputFile" })
            <div class="mb-20 mb-md-10">
                @Html.TextAreaFor(m => m.DescriptionTag, new { @class = "input-md round form-control", @style = "height: 84px;", @placeholder = "Description Tag" })
            </div>

            <div class="clearfix">
                <div class="cf-left-col">
                    <!-- Inform Tip -->
                    <div class="form-tip pt-20">
                        <i class="fa fa-info-circle"></i> All the fields are required
                    </div>
                </div>
                <div class="cf-right-col">
                    <!-- Send Button -->
                    <div class="align-right pt-10">
                        <button type="submit" class="submit_btn btn btn-mod btn-small btn-round" id="submit_btn">Save Tag</button>
                    </div>
                </div>
            </div>
        }
    </div>
</section>