Rhythm/Models/ProjectViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Rhythm.Models
{
    public class ProjectViewModel
    {
        [Display(Name = "Project")]
        public string NameProject { get; set; }
        public string Framework { get; set; }
        public string Database { get; set; }
        public string IDE { get; set; }
        [Display(Name = "Stack technologies")]
        public string StackTechnologies { get; set; }
        public string Url { get; set; }
        public string Date { get; set; }
        public string Description { get; set; }
    }
}

Rhythm/Areas/ChiefAdmin/Controllers/DeleteController.cs
using Rhythm.BL.Interfaces;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace Rhythm.Areas.ChiefAdmin.Controllers
{
    [Authorize]
    public class DeleteController : DefaultController
    {
        public DeleteController(IPostProvider postProvider, ICategoryProvider categoryProvider, ITagProvider tagProvider,
            ICommentProvider commentProvider)
        {
            _postProvider = postProvider;
            _categoryProvider = categoryProvider;
            _tagProvider = tagProvider;
            _commentProvider = commentProvider;

        }


        public async Task<ActionResult> Post(int id)
        {
            var post = await _postProvider.GetPostAsync(id);

            await _postProvider.DeletePostAsync(post);

            return RedirectToAction("listPosts", "Home");
        }


        public async Task<ActionResult> Tag(int id)
        {
            var tag = await _tagProvider.GetTagAsync(id);

            await _tagProvider.DeleteTagAsync(tag);

            return RedirectToAction("listTags", "Home");
        }

        public async Task<ActionResult> Category(int id)
        {
            var category = await _categoryProvider.GetCategoryAsync(id);

            await _categoryProvider.DeleteCategoryAsync(category);

            return RedirectToAction("listCategories", "Home");
        }

        public async Task<ActionResult> Comment(int id)
        {
            var comment = await _commentProvider.GetCommentAsync(id);

            await _commentProvider.DeleteCommentAsync(comment);

            return RedirectToAction("listComments", "Home");
        }

        public async Task<ActionResult> Image(int id)
        {
            var post = await _postProvider.GetPostAsync(id);

            if ((System.IO.File.Exists(post.ImagePath)))
            {
                System.IO.File.Delete(post.ImagePath);
                await _postProvider.RemoveImageByPostAsync(post);
            }

            return RedirectToAction("Image", "Update", new { id = id });
        }
    }
}

Rhythm/Areas/ChiefAdmin/Controllers/EditController.cs
using Rhythm.Areas.ChiefAdmin.Models;
using Rhythm.BL.Interfaces;
using Rhythm.Mappers.ChiefAdmin;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace Rhythm.Areas.ChiefAdmin.Controllers
{
    [Authorize]
    public class EditController : DefaultController
    {
        private TagAdminMapper _tagMapper;
        private CategoryAdminMapper _categoryMapper;
        private PostAdminMapper _postMapper;

        public EditController(IPostProvider postProvider, ICategoryProvider categoryProvider, ITagProvider tagProvider,
            ICommentProvider commentProvider, TagAdminMapper tagMapper, CategoryAdminMapper categoryMapper,
            PostAdminMapper postMapper)
        {
            _postProvider = postProvider;
            _categoryProvider = categoryProvider;
            _tagProvider = tagProvider;
            _commentProvider = commentProvider;
            _tagMapper = tagMapper;
            _categoryMapper = categoryMapper;
            _postMapper = postMapper;

        }

        #region post
        public async Task<ActionResult> Post()
        {
            await DropDownListCategory();
            await TagData();

            return View();
        }

        [HttpPost]
        [ValidateInput(false)]
        public async Task<ActionResult> Post(PostAdminViewModel postViewModel, int[] selectedTag)
        {
            var tags = await _tagProvider.GetTagsByIdAsync(selectedTag);
            var categories = await _categoryProvider.GetCategoriesAsync();

            var category = categories.FirstOrDefault(m => m.Id == postViewModel.CategoryId);

            var post = _postMapper.ToPost(postViewModel, tags, category);

            var toPost = await _postProvider.AddPostAsync(post);
            await _postProvider.AddReferencedToPost(toPost, selectedTag, postViewModel.CategoryId);

            return RedirectToAction("Index", "Home");
        }
        #endregion

        #region tag
        public ActionResult Tag()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Tag(TagAdminViewModel tagViewModel)
        {
            var tag = _tagMapper.ToTag(tagViewModel);

            await _tagProvider.AddTagAsync(tag);

            return RedirectToAction("Index", "Home");
        }
        #endregion  Tag

        #region category
        public ActionResult Category()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Category(CategoryAdminViewModel categoryViewModel)
        {
            var category = _categoryMapper.ToCategory(categoryViewModel);

            await _categoryProvider.AddCategoryAsync(category);

            return RedirectToAction("Index", "Home");
        }
        #endregion

        #region drop
        private async Task TagData()
        {
            var tags = await _tagProvider.GetTagsAsync();
            var tagsViewModel = _tagMapper.ToTagsViewModel(tags);

            ViewBag.Tag = tagsViewModel;
        }

        private async Task DropDownListCategory(object selectedItem = null)
        {
            var categories = from m in await _categoryProvider.GetCategoriesAsync()
                             orderby m.Id
                             select m;
            var categoriesViewModel = _categoryMapper.ToCategoriesViewModel(categories);

            ViewBag.Category = new SelectList(categoriesViewModel, "Id", "Name", selectedItem);
        }
        #endregion
    }
}

Rhythm/Areas/ChiefAdmin/Controllers/ProjectsController.cs
using System.Threading.Tasks;
using System.Web.Mvc;
using Rhythm.BL.Interfaces;
using Rhythm.Mappers.ChiefAdmin;
using Rhythm.Areas.ChiefAdmin.Models;
using System.Linq;

namespace Rhythm.Areas.ChiefAdmin.Controllers
{
    [Authorize]
    public class ProjectsController : DefaultController
    {
        private ProjectAdminMapper _projectMapper;

        public ProjectsController(IProjectProvider projectProvider, IPortfolioProvider portfolioProvider, ProjectAdminMapper projectMapper)
        {
            _projectProvider = projectProvider;
            _portfolioProvider = portfolioProvider;
            _projectMapper = projectMapper;
        }

        public async Task<ActionResult> Index()
        {
            var projects = await _projectProvider.GetListProjectsAsync();
            var projectsViewModel = _projectMapper.ToProjectsViewModel(projects);

            return View(projectsViewModel);
        }

        public async Task<ActionResult> Details(int id)
        {
            var project = await _projectProvider.GetProjectAsync(id);
            var projectViewModel = _projectMapper.ToProjectViewModel(project);

            return View(projectViewModel);
        }

        public async Task<ActionResult> Create()
        {
            await DropDownListPortfoliosAsync();

            return View();
        }

        [HttpPost]
        [ValidateInput(false)]
        public async Task<ActionResult> Create(ProjectAdminViewModel projectViewModel)
        {
            if (ModelState.IsValid)
            {
                var project = _projectMapper.ToProject(projectViewModel);
                await _projectProvider.CreateProjectAsync(project, projectViewModel.PortfolioId);

                return RedirectToAction("Index");
            }

            await DropDownListPortfoliosAsync(projectViewModel.PortfolioId);

            return View(projectViewModel);
        }

        public async Task<ActionResult> Edit(int id)
        {
            var project = await _projectProvider.GetProjectAsync(id);
            var projectViewModel = _projectMapper.ToProjectViewModel(project);

            await DropDownListPortfoliosAsync(projectViewModel.PortfolioId);

            return View(projectViewModel);
        }

        [HttpPost]
        [ValidateInput(false)]
        public async Task<ActionResult> Edit(ProjectAdminViewModel projectViewModel)
        {
            if (ModelState.IsValid)
            {
                var project = _projectMapper.ToProject(projectViewModel);
                await _projectProvider.EditProjectAsync(project, projectViewModel.PortfolioId);

                return RedirectToAction("Index");
            }

            await DropDownListPortfoliosAsync(projectViewModel.PortfolioId);

            return View(projectViewModel);
        }

        public async Task<ActionResult> Delete(int id)
        {
            var project = await _projectProvider.GetProjectAsync(id);
            var projectViewModel = _projectMapper.ToProjectViewModel(project);

            return View(projectViewModel);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            await _projectProvider.DeleteProjectAsync(id);

            return RedirectToAction("Index");
        }

        #region drop
        private async Task DropDownListPortfoliosAsync(object selectedItem = null)
        {
            var query = from m in await _portfolioProvider.GetPortfoliosAsync()
                        orderby m.Id
                        select m;

            ViewBag.PortfolioId = new SelectList(query, "Id", "NamePortfolio", selectedItem);
        }
        #endregion
    }
}

Rhythm/Areas/ChiefAdmin/Views/Projects/Create.cshtml
@model Rhythm.Areas.ChiefAdmin.Models.ProjectAdminViewModel

@{
    Layout = "~/Areas/ChiefAdmin/Views/Shared/_Layout.cshtml";
}
<h2 class="align-center font-alt uppercase">Create Project</h2>
<!-- Section -->
<section class="page-section">
    <div class="container relative">
        <div class="row">
            <!-- Content -->
            <div class="col-lg-12">
                <div>
                    <a href="@Url.Action("Index", "Projects")" class="submit_btn btn btn-mod btn-small btn-round" id="submit_btn"> Back to List </a>
                </div>
                <br />
                @using (Html.BeginForm("Create", "Projects", FormMethod.Post, new { @role = "form", @class = "form" }))
                {

                    <div class="form-horizontal">
                        <h4>Portfolio</h4>
                        <hr />
                        <div class="form-group">
                            @Html.LabelFor(model => model.NameProject, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.NameProject, new { htmlAttributes = new { @name = "NameProject", @id = "NameProject", @class = "input-md form-control" } })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Framework, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Framework, new { htmlAttributes = new { @name = "Framework", @id = "Framework", @class = "input-md form-control" } })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Database, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Database, new { htmlAttributes = new { @name = "Database", @id = "Database", @class = "input-md form-control" } })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.IDE, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.IDE, new { htmlAttributes = new { @name = "IDE", @id = "IDE", @class = "input-md form-control" } })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.StackTechnologies, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.TextAreaFor(model => model.StackTechnologies, new { htmlAttributes = new { @name = "StackTechnologies", @id = "StackTechnologies", @class = "input-md form-control" } })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Url, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.TextAreaFor(model => model.Url, new { htmlAttributes = new { @name = "Url", @id = "Url", @class = "input-md form-control" } })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @name = "Date", @id = "Date", @class = "input-md form-control" } })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.TextAreaFor(model => model.Description, new { htmlAttributes = new { @name = "Description", @id = "Description", @class = "input-md form-control" } })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.PortfolioId, "PortfolioId", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownList("PortfolioId", null, htmlAttributes: new { @class = "input-md form-control" })
                            </div>
                        </div>

                        <div class="clearfix">
                            <div class="cf-left-col">
                                <!-- Inform Tip -->
                                <div class="form-tip pt-20">
                                    <i class="fa fa-info-circle"></i> All the fields are required
                                </div>
                            </div>
                            <div class="cf-right-col">
                                <!-- Send Button -->
                                <div class="align-right pt-10">
                                    <button type="submit" class="submit_btn btn btn-mod btn-small btn-round" id="submit_btn">Create Project</button>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</section>

@section scripts {
    <script src="~/Scripts/ckeditor/ckeditor.js"></script>
    <script>
        var editor = CKEDITOR.instances['StackTechnologies'];
        if (editor) { editor.destroy(true); }
        CKEDITOR.replace('StackTechnologies', { enterMode: CKEDITOR.ENTER_BR, });
    </script>

    <script>
        var editor = CKEDITOR.instances['Description'];
        if (editor) { editor.destroy(true); }
        CKEDITOR.replace('Description', { enterMode: CKEDITOR.ENTER_BR, });
    </script>

    <script>
        var editor = CKEDITOR.instances['Url'];
        if (editor) { editor.destroy(true); }
        CKEDITOR.replace('Url', { enterMode: CKEDITOR.ENTER_BR, });
    </script>
}

Rhythm/Areas/ChiefAdmin/Views/Projects/Delete.cshtml
@model Rhythm.Areas.ChiefAdmin.Models.ProjectAdminViewModel

@{
    Layout = "~/Areas/ChiefAdmin/Views/Shared/_Layout.cshtml";
}

<section class="page-section">
    <div class="container relative">
        <div class="row">
            <!-- Content -->
            <div class="col-lg-8">
                <h2 class="align-center font-alt uppercase">Project @Html.DisplayFor(model => model.NameProject)</h2>
                <h2>Delete</h2>

                <h3>Are you sure you want to delete this Project?</h3>

                @using (Html.BeginForm())
            {

                    <div class="form-actions no-color">
                        <input type="submit" value="Delete" class="submit_btn btn btn-mod btn-small btn-round" id="submit_btn" /> |
                        <a href="@Url.Action("Index", "Projects")" class="submit_btn btn btn-mod btn-small btn-round" id="submit_btn"> Back to List </a>
                    </div>
                }

                <div>
                    <h4>Project</h4>
                    <hr />
                    <dl class="dl-horizontal">

                        <dt>
                            @Html.DisplayNameFor(model => model.NameProject):
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.NameProject)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Framework):
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Framework)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Database):
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Database)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.IDE):
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.IDE)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.StackTechnologies):
                        </dt>

                        <dd>
                            @Html.Raw(Model.StackTechnologies)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Url):
                        </dt>

                        <dd>
                            @Html.Raw(Model.Url)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Date):
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Date)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Description):
                        </dt>

                        <dd>
                            @Html.Raw(Model.Description)
                        </dd>
                    </dl>
                </div>
            </div>
        </div>
    </div>
</section>

Rhythm/Areas/ChiefAdmin/Views/Projects/Details.cshtml
@model Rhythm.Areas.ChiefAdmin.Models.ProjectAdminViewModel

@{
    Layout = "~/Areas/ChiefAdmin/Views/Shared/_Layout.cshtml";
}

<section class="page-section">
    <div class="container relative">
        <div class="row">
            <!-- Content -->
            <div class="col-lg-8">
                <h2 class="align-center font-alt uppercase">Details Project @Html.DisplayFor(model => model.NameProject)</h2>
                <h2>Details</h2>

                <p>
                    <div class="form-actions no-color">
                        <a href="@Url.Action("Edit", "Projects", new { id = Model.Id })" class="submit_btn btn btn-mod btn-small btn-round" id="submit_btn"> Edit </a> |
                        <a href="@Url.Action("Index", "Projects")" class="submit_btn btn btn-mod btn-small btn-round" id="submit_btn"> Back to List </a>
                    </div>
                </p>

                <div>
                    <h4>Project</h4>
                    <hr />
                    <dl class="dl-horizontal">

                        <dt>
                            @Html.DisplayNameFor(model => model.NameProject):
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.NameProject)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Framework):
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Framework)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Database):
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Database)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.IDE):
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.IDE)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.StackTechnologies):
                        </dt>

                        <dd>
                            @Html.Raw(Model.StackTechnologies)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Url):
                        </dt>

                        <dd>
                            @Html.Raw(Model.Url)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Date):
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Date)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Description):
                        </dt>

                        <dd>
                            @Html.Raw(Model.Description)
                        </dd>
                    </dl>
                </div>
            </div>
        </div>
    </div>
</section>

Rhythm/Areas/ChiefAdmin/Views/Projects/Edit.cshtml
@model Rhythm.Areas.ChiefAdmin.Models.ProjectAdminViewModel

@{
    Layout = "~/Areas/ChiefAdmin/Views/Shared/_Layout.cshtml";
}

<h2 class="align-center font-alt uppercase"> Edit Project @Html.DisplayFor(model => model.NameProject)</h2>

<section class="page-section">
    <div class="container relative">
        <div class="row">
            <!-- Content -->
            <div class="col-lg-12">
                <div>
                    <a href="@Url.Action("Index", "Projects")" class="submit_btn btn btn-mod btn-small btn-round" id="submit_btn"> Back to List </a>
                </div>
                <br />
                @using (Html.BeginForm("Edit", "Projects", FormMethod.Post, new { @role = "form", @class = "form" }))
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        <h4>Project</h4>
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            @Html.LabelFor(model => model.NameProject, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.NameProject, new { htmlAttributes = new { @name = "NameProject", @id = "NameProject", @class = "input-md form-control" } })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Framework, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Framework, new { htmlAttributes = new { @name = "Framework", @id = "Framework", @class = "input-md form-control" } })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Database, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Database, new { htmlAttributes = new { @name = "Database", @id = "Database", @class = "input-md form-control" } })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.IDE, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.IDE, new { htmlAttributes = new { @name = "IDE", @id = "IDE", @class = "input-md form-control" } })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.StackTechnologies, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.TextAreaFor(model => model.StackTechnologies, new { htmlAttributes = new { @name = "StackTechnologies", @id = "StackTechnologies", @class = "input-md form-control" } })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Url, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.TextAreaFor(model => model.Url, new { htmlAttributes = new { @name = "Url", @id = "Url", @class = "input-md form-control" } })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @name = "Date", @id = "Date", @class = "input-md form-control" } })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.TextAreaFor(model => model.Description, new { htmlAttributes = new { @name = "Description", @id = "Description", @class = "input-md form-control" } })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.PortfolioId, "PortfolioId", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownList("PortfolioId", null, htmlAttributes: new { @class = "input-md form-control" })
                            </div>
                        </div>

                        <div class="clearfix">
                            <div class="cf-left-col">
                                <!-- Inform Tip -->
                                <div class="form-tip pt-20">
                                    <i class="fa fa-info-circle"></i> All the fields are required
                                </div>
                            </div>
                            <div class="cf-right-col">
                                <!-- Send Button -->
                                <div class="align-right pt-10">
                                    <button type="submit" class="submit_btn btn btn-mod btn-small btn-round" id="submit_btn">Save Project</button>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</section>


@section scripts {
    <script src="~/Scripts/ckeditor/ckeditor.js"></script>
    <script>
        var editor = CKEDITOR.instances['StackTechnologies'];
        if (editor) { editor.destroy(true); }
        CKEDITOR.replace('StackTechnologies', { enterMode: CKEDITOR.ENTER_BR, });
    </script>

    <script>
        var editor = CKEDITOR.instances['Description'];
        if (editor) { editor.destroy(true); }
        CKEDITOR.replace('Description', { enterMode: CKEDITOR.ENTER_BR, });
    </script>

    <script>
        var editor = CKEDITOR.instances['Url'];
        if (editor) { editor.destroy(true); }
        CKEDITOR.replace('Url', { enterMode: CKEDITOR.ENTER_BR, });
    </script>
}