Rhythm/Areas/ChiefAdmin/Models/PostViewModel.cs
using Rhythm.Domain.Model;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Rhythm.Areas.ChiefAdmin.Models
{
    public class PostViewModel
    {
        [Required(ErrorMessage = "the field are required!")]
        public string NameSenderPost { get; set; }
        [Required(ErrorMessage = "the field are required!")]
        public string Title { get; set; }
        [Required(ErrorMessage = "the field are required!")]
        public string ShortDescription { get; set; }
        [Required(ErrorMessage = "the field are required!")]
        public string DescriptionPost { get; set; }
        [Required(ErrorMessage = "the field are required!")]
        public string UrlSlug { get; set; }
        [Required(ErrorMessage = "the field are required!")]
        public bool Published { get; set; }
        [Required(ErrorMessage = "the field are required!")]
        public int Category { get; set; }
        public Category Category1 { get; set; }
        public byte[] ImageData { get; set; }
        public string ImageMime { get; set; }

        public int ID { get; set; }
        public DateTime PostedOn { get; set; }
        public Nullable<DateTime> Modified { get; set; }
        public Nullable<int> CountComments { get; set; }
        public ICollection<Comment> Comments { get; set; }
        public ICollection<Tag> Tags { get; set; }
    }
}

Rhythm/Models/PostViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Rhythm.Models
{
    public class PostViewModel
    {
        public int Id { get; set; }
        public string NameSenderPost { get; set; }
        public string Title { get; set; }
        public string ShortDescription { get; set; }
        public string DescriptionPost { get; set; }
        public string UrlSlug { get; set; }
        public bool Published { get; set; }
        public DateTime PostedOn { get; set; }
        public DateTime Modified { get; set; }
        public byte[] ImageData { get; set; }
        public string ImagePath { get; set; }
        public string ImageMime { get; set; }
        public int CountComments { get; set; }
    }
}

Rhythm/Areas/ChiefAdmin/Controllers/EditContentController.cs
using AutoMapper;
using Rhythm.Areas.ChiefAdmin.Models;
using Rhythm.Domain.Abstract;
using Rhythm.Domain.Model;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Rhythm.Areas.ChiefAdmin.Controllers
{

    public class EditContentController : DefaultController
    {
        public EditContentController(IRepository repository)
        {
            this.repository = repository;
        }
        // GET: ChiefAdmin/AddContent

        public ActionResult Post()
        {
            CategoryDropDownList Categories = new CategoryDropDownList
            {
                Category = repository.Category
                    .OrderBy(c => c.ID)
                    .ToList()
            };

            TagDropDownList Tags = new TagDropDownList
            {
                Tag = repository.Tag
                .OrderBy(c => c.ID)
                .ToList()
            };

            ViewBag.Category = new SelectList(Categories.Category, "ID", "Name", 1);
            ViewBag.Tag = new SelectList(Tags.Tag, "ID", "Name", 1);
            return View();
        }


        public ICollection<PostTag> TagCollection(List<int> item)
        {
            var tagList = new List<PostTag>();

            foreach (var i in item)
            {
                var q = repository.Tag.FirstOrDefault(t => t.PostTags == null);
                var tt = repository.Post.FirstOrDefault(p => p.PostTags == null);

                tagList.Add();
            }
            //if (tags.Length > 0)
            //{
            //    post.Tags = new List<Tag>();

            //    foreach (var tag in tags)
            //    {
            //        post.Tags.Add(_blogRepository.Tag(int.Parse(tag.Trim())));
            //    }
            //}
            return tagList;
        }

        [HttpPost]
        public ActionResult Post(PostViewModel post)
        {
            if (ModelState.IsValid)
            {
                try
                {

                    var tagList = TagCollection(post.Tag);

                    byte[] image = new byte[post.imageData.ContentLength];
                    post.imageData.InputStream.Read(image, 0, image.Length);

                    Post p = new Post
                    {
                        NameSenderPost = post.NameSenderPost,
                        Title = post.Title,
                        ShortDescription = post.ShortDescription,
                        DescriptionPost = post.DescriptionPost,
                        UrlSlug = post.UrlSlug,
                        Published = post.Published,
                        Category = post.Category,
                        ImageData = image,
                        ImageMime = post.ImageMime,
                        PostTags = 
                                         
                        
                    };

                    repository.AddPost(p);
                }
                catch (Exception ex)
                {
                    //TODO: NLog
                }
            }
            return RedirectToAction("Index", "Home");
        }

        public ActionResult EditTag()
        {

            return View();
        }

        [HttpPost]
        public ActionResult EditTag(TagViewModel tag)
        {

            return View();
        }

        public ActionResult EditCategory()
        {

            return View();
        }

        [HttpPost]
        public ActionResult EditCategory(CategoryViewModel category)
        {

            return View();
        }
    }
}

Rhythm/Controllers/PostsController.cs
using NLog;
using Rhythm.BL.Interfaces;
using Rhythm.Domain.Entities;
using Rhythm.Mappers;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace Rhythm.Controllers
{
    public class PostsController : DefaultController
    {
        private static NLog.Logger logger = LogManager.GetCurrentClassLogger();
        private PostMapper _postMapper;

        public PostsController(IPostProvider postProvider, PostMapper postMapper)
        {
            _postProvider = postProvider;
            _postMapper = postMapper;
        }

        public async Task<ViewResult> Index(int page = 1)
        {
            var post = await _postProvider.GetPostsAsync();
            var postListViewModel = _postMapper.ToPostListViewModel(post, page);

            return View(postListViewModel);
        }

        public async Task<ActionResult> Post(int id, bool? flag)
        {
            var posts = await _postProvider.GetPostsAsync();
            int count = posts.Where(p => p.Published == true).Max(m => m.Id);

            var post = await _postProvider.GetPostWithConditionAsync(id, flag);

            var postSingleViewModel = _postMapper.ToPostSingleViewModel(post, count);

            return View(postSingleViewModel);
        }

        public async Task<FileContentResult> GetImage(int id)
        {
            var post = await _postProvider.GetPostAsync(id);

            if (post.ImagePath != null)
            {
                var dataByte = System.IO.File.ReadAllBytes(post.ImagePath);

                return File(dataByte, "image/png");
            }

            return null;
        }
    }
}

Rhythm/Areas/ChiefAdmin/Views/EditContent/EditPost.cshtml
@model Rhythm.Areas.ChiefAdmin.Models.PostViewModel

@{
    Layout = "~/Areas/ChiefAdmin/Views/Shared/_Layout.cshtml";
}
<!-- Section -->
<section class="page-section">
    <div class="container relative">

        <!-- Form -->
        @using (Html.BeginForm("EditPost", "EditContent", FormMethod.Post, new { enctype = "multipart/form-data", @role = "form", @class = "form" }))
        {

            @Html.Label("Name: ", new { @for = "exampleInputFile" })
            <div class="mb-20 mb-md-10">
                <!-- Name -->
                @Html.TextBoxFor(m => m.NameSenderPost, new { @name = "Name", @id = "Name", @class = "input-md form-control", @placeholder = "Name" })
            </div>

            @Html.Label("Title: ", new { @for = "exampleInputFile" })
            <div class="mb-20 mb-md-10">
                <!-- Title -->
                @Html.TextBoxFor(m => m.Title, new { @name = "Title", @id = "Title", @class = "input-md form-control", @placeholder = "Title" })
            </div>

            @Html.Label("Short Description: ", new { @for = "exampleInputFile" })
            <div class="mb-20 mb-md-10">
                @Html.TextAreaFor(m => m.ShortDescription, new { @name = "ShortDescription", @id = "ShortDescription", @class = "input-md round form-control", @style = "height: 84px;", @placeholder = "Short Description" })
            </div>

            @Html.Label("Post: ", new { @for = "exampleInputFile" })
            <div class="mb-20 mb-md-10">
                @Html.TextAreaFor(m => m.DescriptionPost, new { @name = "PostDescription", @id = "PostDescription", @class = "input-md round form-control", @style = "height: 84px;", @placeholder = "Post" })
            </div>

            @Html.Label("Url Slug: ", new { @for = "exampleInputFile" })
            <div class="mb-20 mb-md-10">
                <!-- URL -->
                @Html.TextBoxFor(m => m.UrlSlug, new { @name = "UrlSlug", @id = "UrlSlug", @class = "input-md form-control", @placeholder = "Url Slug" })
            </div>
            @Html.Label("Published?: ", new { @for = "exampleInputFile" })
            <div class="mb-20 mb-md-10">
                <label class="checkbox-inline">
                    @Html.CheckBoxFor(m => m.Published)
                </label>
            </div>

            @Html.Label("Choose category: ", new { @for = "exampleInputFile" })
            <div class="mb-20 mb-md-10">
                @Html.DropDownList("Category", (IEnumerable<SelectListItem>) ViewBag.Category)
            </div>

            @Html.Label("Choose Tags: ", new { @for = "exampleInputFile" })
            <div class="mb-20 mb-md-10">
                @Html.ListBox("Tag", (IEnumerable<SelectListItem>) ViewBag.Tag, new { size = 7, @class = "form-control" })
            </div>

            @Html.Label("Photo Description: ", new { @for = "exampleInputFile" })
            <div class="mb-20 mb-md-10">
                <!-- Description -->
                @Html.TextBoxFor(m => m.ImageMime, new { @name = "ImageMime", @id = "ImageMime", @class = "input-md form-control", @placeholder = "Photo Description" })
            </div>

            @Html.Label("Load Photo: ")
            <div class="mb-20 mb-md-10">
                @Html.TextBoxFor(m => m.imageData, new { @type = "file", id = "ImageData", @value = "Save" })
                <p class="help-block">
                    Choose photo
                </p>
            </div>
            <div class="clearfix">
                <div class="cf-left-col">
                    <!-- Inform Tip -->
                    <div class="form-tip pt-20">
                        <i class="fa fa-info-circle"></i> All the fields are required
                    </div>
                </div>
                <div class="cf-right-col">
                    <!-- Send Button -->
                    <div class="align-right pt-10">
                        <button type="submit" class="submit_btn btn btn-mod btn-medium btn-round" id="submit_btn">Edit Post</button>
                    </div>
                </div>
            </div>
        }
    </div>
</section>

Rhythm/Areas/ChiefAdmin/Views/EditContent/Post.cshtml
@model Rhythm.Areas.ChiefAdmin.Models.PostViewModel

@{
    Layout = "~/Areas/ChiefAdmin/Views/Shared/_Layout.cshtml";
}
<!-- Section -->
<section class="page-section">
    <div class="container relative">

        <!-- Form -->
        @using (Html.BeginForm("Post", "EditContent", FormMethod.Post, new { enctype = "multipart/form-data", @role = "form", @class = "form" }))
        {

            @Html.Label("Name: ", new { @for = "exampleInputFile" })
            <div class="mb-20 mb-md-10">
                <!-- Name -->
                @Html.TextBoxFor(m => m.NameSenderPost, new { @name = "Name", @id = "Name", @class = "input-md form-control", @placeholder = "Name" })
            </div>

            @Html.Label("Title: ", new { @for = "exampleInputFile" })
            <div class="mb-20 mb-md-10">
                <!-- Title -->
                @Html.TextBoxFor(m => m.Title, new { @name = "Title", @id = "Title", @class = "input-md form-control", @placeholder = "Title" })
            </div>

            @Html.Label("Short Description: ", new { @for = "exampleInputFile" })
            <div class="mb-20 mb-md-10">
                @Html.TextAreaFor(m => m.ShortDescription, new { @name = "ShortDescription", @id = "ShortDescription", @class = "input-md round form-control", @style = "height: 84px;", @placeholder = "Short Description" })
            </div>

            @Html.Label("Post: ", new { @for = "exampleInputFile" })
            <div class="mb-20 mb-md-10">
                @Html.TextAreaFor(m => m.DescriptionPost, new { @name = "PostDescription", @id = "PostDescription", @class = "input-md round form-control", @style = "height: 84px;", @placeholder = "Post" })
            </div>

            @Html.Label("Url Slug: ", new { @for = "exampleInputFile" })
            <div class="mb-20 mb-md-10">
                <!-- URL -->
                @Html.TextBoxFor(m => m.UrlSlug, new { @name = "UrlSlug", @id = "UrlSlug", @class = "input-md form-control", @placeholder = "Url Slug" })
            </div>
            @Html.Label("Published?: ", new { @for = "exampleInputFile" })
            <div class="mb-20 mb-md-10">
                <label class="checkbox-inline">
                    @Html.CheckBoxFor(m => m.Published)
                </label>
            </div>

            @Html.Label("Choose category: ", new { @for = "exampleInputFile" })
            <div class="mb-20 mb-md-10">
                @Html.DropDownList("Category", (IEnumerable<SelectListItem>) ViewBag.Category)
            </div>

            @Html.Label("Choose Tags: ", new { @for = "exampleInputFile" })
            <div class="mb-20 mb-md-10">
                @Html.ListBoxFor(m => m.Tag, (IEnumerable<SelectListItem>) ViewBag.Tag, new { size = 7, @class = "form-control" })
            </div>

            @Html.Label("Photo Description: ", new { @for = "exampleInputFile" })
            <div class="mb-20 mb-md-10">
                <!-- Description -->
                @Html.TextBoxFor(m => m.ImageMime, new { @name = "ImageMime", @id = "ImageMime", @class = "input-md form-control", @placeholder = "Photo Description" })
            </div>

            @Html.Label("Load Photo: ")
            <div class="mb-20 mb-md-10">
                @Html.TextBoxFor(m => m.imageData, new { @type = "file", id = "ImageData", @value = "Save" })
                <p class="help-block">
                    Choose photo
                </p>
            </div>
            <div class="clearfix">
                <div class="cf-left-col">
                    <!-- Inform Tip -->
                    <div class="form-tip pt-20">
                        <i class="fa fa-info-circle"></i> All the fields are required
                    </div>
                </div>
                <div class="cf-right-col">
                    <!-- Send Button -->
                    <div class="align-right pt-10">
                        <button type="submit" class="submit_btn btn btn-mod btn-medium btn-round" id="submit_btn">Edit Post</button>
                    </div>
                </div>
            </div>
        }
    </div>
</section>